### ISSUE TITLE
Highlight the Sq'irk tree when its time to run instead of having a notification

### ISSUE THREAD

**Issue by zeakzz** [LlemonDuck/one-click-summer-garden#4]
I think this would be a better way to notify when the cycle is ready than a windows notification.

**Comment by LlemonDuck** [comment]
The first and third elementals will already highlight blue (by default) when it's time to go, since they're the ones you'll need to watch for timing. If you're not a fan of the windows notifications, they can be disabled from the config

**Comment by LlemonDuck** [comment]
You can now enable a countdown on the tree itself in the config, which will also highlight the tree as a whole.
