### ISSUE TITLE
Add menu entry swaps

### ISSUE THREAD

**Issue by thebinaryeagle** [LlemonDuck/one-click-summer-garden#6]
It would be very helpful to have a menu entry swap option to change the sq'irk juice to 'Use' instead of 'Drink' to prevent accidents while drinking stamina potions or fletching while running the garden. I tried using Hydrox's "Don't eat it!" plugin but that messes with stamina potions and equipping bolts you're fletching so it's not an ideal fix.

Also, though less useful, a swap so the 'Teleport' option is the left click for the Apprentice in Al Kharid would be nice as well.

I hope these aren't too out of scope for your plugin, they would definitely be nice QoL for the long grind ahead.

**Comment by LlemonDuck** [comment]
This is now possible with the default Menu Entry Swapper via custom swaps, so I'm going to mark this as no longer planned.
