### ISSUE TITLE
Low Stamina Threshold not notifying until run hits zero

### ISSUE THREAD

**Issue by HookedLivesMatter** [LlemonDuck/one-click-summer-garden#8]
I have low stamina threshold option configured to 20 but I dont get a notification about my run energy level until im at 0, is this a bug or am I the only person experiencing this?

**Comment by LlemonDuck** [comment]
There is a check which prevents the stamina warning going off if you already have a stamina active. Are you reaching 0 energy with the endurance effect still going?

**Comment by HookedLivesMatter** [comment]
No, usually the endurance effect has expired by that point. I just switched to runelite's idle notification setting which warns you when your below 20 energy as a replacement and that is working for me. Before I had it set to 100 (meaning it was off). Maybe the two addons were conflicting with each other?

**Comment by xConde** [comment]
The issue remains unresolved. Even with super energy potions, notifications on, and the client focused, the alert doesn't seem to be working.

**Comment by cipscript** [comment]
Also have this problem

**Comment by LlemonDuck** [comment]
apologies for the long delay, this has now been fixed and released
